name: Run PHP Parallel Lint, PHP CodeSniffer, and PHPUnit tests

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHP Parallel Lint
      run: vendor/bin/parallel-lint . --exclude vendor

    - name: Run phpcs
      run: vendor/bin/phpcs -s

    - name: Run test suite
      run: XDEBUG_MODE=coverage vendor/bin/phpunit

    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./.artifacts
        fail_ci_if_error: true
        flags: phpunit
        verbose: true
